name: run unit tests of the teseo and nmea libs
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'develop'
  #    - 'main'
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout test_gps_teseo
        uses: actions/checkout@v4
        with:
          path: test_gps_teseo
          submodules: true
          repository: jancumps/test_gps_teseo

      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build

          sudo apt-get install cmake
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install gcc-14
          gcc --version
          whereis gcc
          whereis gcc-14
          ls -la /usr/bin | grep g++

      - name: Build Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          echo ${{ github.ref }}
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/x86_64-linux-gnu-gcc-14 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/x86_64-linux-gnu-g++-14 -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..

      - name: Test Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          cd build
          chmod +x ./test_class_module
          ./test_class_module
          cd ..
