name: run unit tests of the teseo and nmea libs
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'develop'
  #    - 'main'
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout test_gps_teseo
        uses: actions/checkout@v4
        with:
          path: test_gps_teseo
          submodules: true
          repository: jancumps/test_gps_teseo

      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build

          sudo apt-get install cmake
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install gcc-14
          ls -lrta /usr/local/
          sudo update-alternatives --remove-all gcc
          sudo update-alternatives --remove-all g++
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-14.2.0/bin/g++14.2.0 14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-14.2.0/bin/gcc14.2.0 14
          
      - name: Build Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          echo ${{ github.ref }}
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..
          ls -lrt build/*.uf2

      - name: Test Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          cd build
          cmake --test .
          cd ..
