name: run unit tests
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'develop'
  #    - 'main'
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-26.04
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout test_gps_teseo
        uses: actions/checkout@v7
        with:
          path: test_gps_teseo
          submodules: false
          repository: jancumps/test_gps_teseo

      - name: Checkout pico_gps_teseo
        uses: actions/checkout@v7
        with:
          path: test_gps_teseo/pico_gps_teseo
          submodules: true
          
      - name: Checkout pico-sdk/develop
        uses: actions/checkout@v7
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: test_gps_teseo/pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/test_gps_teseo/pico-sdk
        run: git submodule update --init

      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build

          sudo apt-get install cmake
          sudo add-apt-repository universe
          sudo apt update
              
          sudo apt install gcc-arm-none-eabi
          arm-none-eabi-c++ --version

          curl -Lo picotool-2.3.0-x86_64-lin.tar.gz "https://github.com/raspberrypi/pico-sdk-tools/releases/download/v2.3.0-0/picotool-2.3.0-x86_64-lin.tar.gz"
          sudo mkdir /opt/picotool
          sudo tar -xvzf picotool-2.3.0-x86_64-lin.tar.gz --strip-components=1 -C /opt/picotool
          sudo chmod +x /opt/picotool/picotool
          ls -lrta /opt/picotool
          ls -lrta /opt/picotool/picotool
          echo 'export PATH=$PATH:/opt/picotool' | sudo tee -a /etc/profile.d/picotool.sh
          export PATH=$PATH:/opt/picotool
          source /etc/profile

      - name: Fetch pico_gps_teseo libs
        working-directory: ${{github.workspace}}/test_gps_teseo/pico_gps_teseo
        shell: bash
        run: |
          echo ${{ github.ref }}
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DPICO_PLATFORM=rp2040 -DPICO_BOARD=pico -DPICOTOOL_DIR=/opt/picotool -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/arm-none-eabi-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/arm-none-eabi-g++ -DPICO_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi/bin -DPICO_SDK_PATH=../../pico-sdk -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico
          cmake --build .
          cd ..
          ls -lrt build/*.uf2

      - name: Build Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          echo ${{ github.ref }}
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..

      - name: Test Project
        working-directory: ${{github.workspace}}/test_gps_teseo
        shell: bash
        run: |
          cd build
          ctest
          # chmod +x ./test_class_module
          # ./test_class_module
          cd ..
